version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: yeshuapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yeshuapp
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
